name: Deploy to Clojars

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.2
        with:
          cli: 1.11.1.1149

      - name: Build jar
        run: clojure -T:build ci

      - name: Deploy to clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -T:build deploy

      - name: Check version
        id: version
        run: cat .version

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: 1.1.2-SNAPSHOT
          token: ${{ secrets.GITHUB_TOKEN }}
